export type DownloadStatus =
  | 'queued'
  | 'downloading'
  | 'processing'
  | 'completed'
  | 'error'
  | 'cancelled'

export type Destination = 'server' | 'direct'

export type Download = {
  id: string
  url: string
  title: string
  filename: string | null
  filepath: string | null
  status: DownloadStatus
  percent: number
  downloadedBytes: number
  totalBytes: number | null
  speed: number | null
  eta: number | null
  error: string | null
  preset: string
  playlist: boolean
  destination: Destination
  delivered: boolean
  createdAt: number
  finishedAt: number | null
}

export type CookieCloudSettings = {
  serverUrl: string
  uuid: string
  password: string
  autoSyncMinutes: number
}

export type CookieCloudStatus = {
  lastSyncAt: number | null
  cookieCount: number
  domainCount: number
  lastError: string | null
}

export type Settings = {
  downloadDir: string
  ytdlpPath: string
  // Path to the ffmpeg binary (or its directory). Empty falls back to the
  // static build bundled via the ffmpeg-static package.
  ffmpegPath: string
  extraArgs: string
  cookieCloud: CookieCloudSettings
}

export type NewDownloadRequest = {
  url: string
  preset?: string
  playlist?: boolean
  destination?: Destination
  // Fetch and embed subtitles. Two language tracks are downloaded (subLang1 and
  // subLang2, e.g. "en" and "zh-Hans"); when both exist a third bilingual track
  // is generated by merging them. All available tracks are embedded as
  // selectable streams, with the bilingual one set as the default. Covers both
  // OP-uploaded and YouTube auto-generated/auto-translated captions.
  subtitles?: boolean
  subLang1?: string
  subLang2?: string
  // Burn one subtitle track permanently into the picture (re-encodes the video)
  // so it shows in any player, including browsers and QuickTime. Not selectable.
  // burnLang picks which track: "bilingual" (default) or one of the two codes.
  burnSubs?: boolean
  burnLang?: string
  // Output container to remux into (e.g. "mp4", "mkv", "webm"). Empty leaves
  // yt-dlp's chosen container as-is.
  container?: string
}
