export type DownloadStatus =
  | 'queued'
  | 'downloading'
  | 'processing'
  | 'uploading'
  | 'completed'
  | 'error'
  | 'cancelled'

// 'quark' downloads to the server, uploads to Quark Drive, then deletes the
// local copy so it uses no server disk
export type Destination = 'server' | 'direct' | 'quark'

export type Download = {
  id: string
  url: string
  title: string
  filename: string | null
  filepath: string | null
  status: DownloadStatus
  percent: number
  downloadedBytes: number
  totalBytes: number | null
  speed: number | null
  eta: number | null
  error: string | null
  preset: string
  playlist: boolean
  destination: Destination
  delivered: boolean
  createdAt: number
  finishedAt: number | null
}

export type CookieCloudSettings = {
  serverUrl: string
  uuid: string
  password: string
  autoSyncMinutes: number
}

export type CookieCloudStatus = {
  lastSyncAt: number | null
  cookieCount: number
  domainCount: number
  lastError: string | null
}

export type QuarkSettings = {
  // Which Quark login client was used (see QUARK_CLIENTS)
  client: string
  // Session cookie, populated by QR login (or pasted manually)
  cookie: string
  // Destination folder in Quark ("0" is the drive root); folderName is for display
  folderId: string
  folderName: string
}

export type Settings = {
  downloadDir: string
  ytdlpPath: string
  // Path to the ffmpeg binary (or its directory). Empty falls back to the
  // static build bundled via the ffmpeg-static package.
  ffmpegPath: string
  extraArgs: string
  cookieCloud: CookieCloudSettings
  quark: QuarkSettings
}

export type NewDownloadRequest = {
  url: string
  preset?: string
  playlist?: boolean
  destination?: Destination
  // Fetch and embed subtitles. Two language tracks are downloaded (subLang1 and
  // subLang2, e.g. "en" and "zh-Hans"); when both exist a third bilingual track
  // is generated by merging them. All available tracks are embedded as
  // selectable streams, with the bilingual one set as the default. Covers both
  // OP-uploaded and YouTube auto-generated/auto-translated captions.
  subtitles?: boolean
  subLang1?: string
  subLang2?: string
  // Burn one subtitle track permanently into the picture (re-encodes the video)
  // so it shows in any player, including browsers and QuickTime. Not selectable.
  // burnLang picks which track: "bilingual" (default) or one of the two codes.
  burnSubs?: boolean
  burnLang?: string
  // Output container to remux into (e.g. "mp4", "mkv", "webm"). Empty leaves
  // yt-dlp's chosen container as-is.
  container?: string
  // Prefix the output filename with a zero-padded sequence number. For a
  // playlist this is the starting number and increments per item; required for
  // playlists. Undefined = no prefix.
  seqStart?: number
  // Prepend a translated copy of the title to the filename:
  // "<seq> <translated title> <original title> [id]".
  translateTitle?: boolean
  // Target language for the translated title (e.g. "zh-CN"). Defaults to zh-CN.
  translateTo?: string
}
